-- MySQL Script generated by MySQL Workbench
-- Sun May 19 19:24:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catalogo_musicas
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `catalogo_musicas` DEFAULT CHARACTER SET utf8;
USE `catalogo_musicas`;

-- -----------------------------------------------------
-- Table `catalogo_musicas`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo_musicas`.`artista` (
  `id_artista` INT AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_artista`),
  UNIQUE (`nome`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `catalogo_musicas`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo_musicas`.`album` (
  `id_album` INT AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_lanc` DATE NOT NULL,
  `id_artista` INT NOT NULL,
  PRIMARY KEY (`id_album`),
  UNIQUE (`nome`),
  FOREIGN KEY (`id_artista`)
    REFERENCES `catalogo_musicas`.`artista` (`id_artista`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `catalogo_musicas`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo_musicas`.`genero` (
  `id_genero` INT AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE (`nome`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `catalogo_musicas`.`musicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catalogo_musicas`.`musicas` (
  `id_musica` INT AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `data_lanc` DATE NOT NULL,
  `id_artista` INT NOT NULL,
  `id_album` INT NOT NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id_musica`),
  FOREIGN KEY (`id_artista`)
    REFERENCES `catalogo_musicas`.`artista` (`id_artista`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  FOREIGN KEY (`id_album`)
    REFERENCES `catalogo_musicas`.`album` (`id_album`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  FOREIGN KEY (`id_genero`)
    REFERENCES `catalogo_musicas`.`genero` (`id_genero`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  UNIQUE (`nome`)
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
